# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZNmCPqm8b6Fsqkpu85JTbe-Kk833F3A
"""

def recc(n):
    global custom_arr
    if n == 0:
        return 1
    if n == 1:
        return 1
    if custom_arr[n]:
        return custom_arr[n]
    else:
        custom_arr[n] = recc(n - 1) + recc(n - 2)  # Fibonacci series using memoization
        return custom_arr[n]

def fibonacci_memoization(n):
    global custom_arr
    custom_arr = [False] * (n + 1)
    return recc(n)

input_file = open("/content/drive/MyDrive/cse221_ass08/input2_1.txt", "r")
output_file = open("/content/drive/MyDrive/cse221_ass08/output2_1.txt", "w")
n = int(input_file.readline().strip())
result = fibonacci_memoization(n)
output_file.write(str(result))
input_file.close()
output_file.close()