# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZNmCPqm8b6Fsqkpu85JTbe-Kk833F3A
"""

infile = open("/content/drive/MyDrive/cse221_ass07/input3_2.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass07/output3_2.txt", "w")
l = infile.readlines()
nm = list(map(int, l[0].split(" ")))
n = nm[0]
m = nm[1]
s = []
for i in range(1, len(l)):
    l[i] = l[i].strip("\n")
    elem = l[i]
    subs = list(map(int, elem.split(" ")))
    s.append(subs)
line = ""
p = [-1] * (n+1)
def find_p(p, n):
    if p[n] < 0:
        return n
    else:
        n = p[n]
        return find_p(p, n)
for i in s:
    s = i[0]
    e = i[1]
    sp = find_p(p, s)
    ep = find_p(p, e)
    m = min(p[sp], p[ep])
    if sp == ep:
        pass
    else:
        if p[sp] == m:
            p[sp] += p[ep]
            m += p[ep]
            p[ep] = sp
        else:
            p[ep] += p[sp]
            m += p[sp]
            p[sp] = ep
    line += str(m * (-1)) + "\n"
outfile.writelines(line)