# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZNmCPqm8b6Fsqkpu85JTbe-Kk833F3A
"""

def maxy(a, b):
    if a > b:
        return a
    else:
        return b

def findMax(arr, l, r):
    if l == r:
        return arr[l]
    mid = (l + r) // 2
    left_max = findMax(arr, l, mid)
    right_max = findMax(arr, mid + 1, r)
    return maxy(left_max, right_max)

infile = open("/content/drive/MyDrive/cse221_ass02/input4.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass02/output4.txt", "w")
lis = infile.readlines()
arr = list(map(int, lis[1].split(" ")))
max_elem = findMax(arr, 0, len(arr) - 1)
max_elem = str(max_elem)
outfile.writelines(max_elem)