# -*- coding: utf-8 -*-
"""task1(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZNmCPqm8b6Fsqkpu85JTbe-Kk833F3A
"""

infile = open("/content/drive/MyDrive/cse221_ass02/input1(2).txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass02/output1(2).txt", "w")

lis = infile.readlines()

inp1 = list(map(int, lis[0].split(" ")))
inp2 = list(map(int, lis[1].split(" ")))
f = 0
f2 = 0
for i in range(len(inp2)):
    need = inp1[1] - inp2[i]
    if need in inp2 and f == 0:
        got = need
        indx_1 = i+1
        f = 1
    elif f == 1 and got == inp2[i]:
        lin = f"{indx_1} {i+1}"
        outfile.writelines(lin)
        f2 = 1
        break
if f2 == 0:
    outfile.writelines("IMPOSSIBLE")