# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRWx4BP__DHB2IUv6S6ophtdimag2Edj
"""

#Task_03
infile = open("/content/drive/MyDrive/cse221_ass01/input3.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass01/output3.txt", "w")

def selectionSort(arr, arr_2):
    for i in range(len(arr)):
        l = []
        max_idx = i
        for j in range(i+1, len(arr)):
            if arr[j] > arr[max_idx]:
                max_idx = j
        arr[i], arr[max_idx] = arr[max_idx], arr[i]
        arr_2[i], arr_2[max_idx] = arr_2[max_idx], arr_2[i]
    l.append(arr)
    l.append(arr_2)
    return l

l = infile.readlines()
arr = list(map(int, l[2].split(" ")))
Id = list(map(int, l[1].split(" ")))
ret = selectionSort(arr, Id)
si = ret[1]
marks = ret[0]
line = ""
for i in range(int(l[0])-1):
    line += f"ID: {si[i]} Mark: {marks[i]}\n"
line += f"ID: {si[i+1]} Mark: {marks[i+1]}"
outfile.writelines(line)