# -*- coding: utf-8 -*-
"""task1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRWx4BP__DHB2IUv6S6ophtdimag2Edj
"""

#Task_1(a)
path1 = "/content/drive/MyDrive/cse221_ass01/input1a.txt"
infile = open(path1, "r")
path2 = "/content/drive/MyDrive/cse221_ass01/output1a.txt"
outfile = open(path2, "w")

nums = infile.readlines()
lines = ""
nums[0] = int(nums[0])
for i in range(1, nums[0]+1):
    nums[i] = int(nums[i])
    if nums[i] % 2 == 0:
        eo = "Even"
    else:
        eo = "Odd"
    ln = f"{nums[i]} is an {eo} number."
    if i != nums[0]:
        lines += ln + "\n"
    else:
        lines += ln
outfile.writelines(lines)