# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRWx4BP__DHB2IUv6S6ophtdimag2Edj
"""

#Task_04
infile = open("/content/drive/MyDrive/cse221_ass01/input4.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass01/output4.txt", "w")

l = infile.readlines()
trains = []
dest = []
time = []
dic_time = {}
dic_dest = {}

def selSort(arr1, arr2):
    f = []
    for i in range(len(arr1)):
        max = i
        for j in range(i+1, len(arr1)):
            if arr1[j] > arr1[max]:
                max = j
        arr1[i], arr1[max] = arr1[max], arr1[i]
        arr2[i], arr2[max] = arr2[max], arr2[i]
    f.append(arr1)
    f.append(arr2)
    return f

for t in range(1, len(l)):
    i = l[t].split()
    trains.append(i[0])
    tm = i[len(i)-1]
    tm = tm.replace(":", ".")
    tm = float(tm)
    if i[0] not in dic_time:
        dic_time[i[0]] = [tm]
        dic_dest[i[0]] = [i[len(i)-3]]
    else:
        dic_time[i[0]] += [tm]
        dic_dest[i[0]] += [i[len(i)-3]]
for k, v in dic_time.items():
    temp = selSort(v, dic_dest[k])
    dic_time[k] = temp[0]
    dic_dest[k] = temp[1]
trains.sort()
line = ""
for z in range(len(trains)):
    trn = trains[z]
    tim = dic_time[trn][0]
    dst = dic_dest[trn][0]
    dic_time[trn].remove(tim)
    dic_dest[trn].remove(dst)
    tim = f"{tim:.2f}"
    tim = str(tim).zfill(5)
    tim = tim.replace(".", ":")
    ll = f"{trn} will departure for {dst} at {tim}"
    if z != len(trains)-1:
        line += ll + "\n"
    else:
        line += ll
outfile.writelines(line)