# -*- coding: utf-8 -*-
"""task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZRhVcdIIfr5cQOatRObMOeK463-HhA7Q
"""

#Task-01(a)
infile = open("/content/drive/MyDrive/cse221_ass04/input1a_2.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass04/output1a_2.txt", "w")

matx = []
l = infile.readlines()
nm = list(map(int, l[0].split(" ")))
n = nm[0]
for i in range(n+1):
    temp = []
    for j in range(n+1):
        temp.append(0)
    matx.append(temp)

for elem in l:
    elem = elem.strip("\n")

for e2 in range(1, len(l)):
    l[e2] = list(map(int, l[e2].split(" ")))
    i = l[e2][0]
    j = l[e2][1]
    w = l[e2][2]
    matx[i][j] = w
line = ""
for i in range(len(matx)):
    for j in range(len(matx[i])-1):
        line += str(matx[i][j]) + " "
    line += str(matx[i][j+1]) + "\n"
outfile.writelines(line)