# -*- coding: utf-8 -*-
"""task1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZRhVcdIIfr5cQOatRObMOeK463-HhA7Q
"""

#Task-01(b)
infile = open("/content/drive/MyDrive/cse221_ass04/input1b_3.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass04/output1b_3.txt", "w")

matx = []
l = infile.readlines()
nm = list(map(int, l[0].split(" ")))
n = nm[0]
for elem in l:
    elem = elem.strip("\n")
lis = []
for i in range(n+1):
    temp = f"{i} :"
    lis.append(temp)
for e2 in range(1, len(l)):
    l[e2] = list(map(int, l[e2].split(" ")))
    i = l[e2][0]
    j = l[e2][1]
    w = l[e2][2]
    tup = j, w
    lis[i] += str((j, w))+" "
line = ""
for elem in lis:
    line += elem + "\n"
outfile.writelines(line)