# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WxWCOdGs2ef3fbPXEPlt_bW-J1OzMX4I
"""

def merge(arr, l, mid, r):
    inv = 0
    n1 = mid-l+1
    n2 = r-mid
    a = []
    b = []
    for i in range(n1):
        a.append(arr[l+i])
    for j in range(n2):
        b.append(arr[mid+j+1])
    i = 0
    j = 0
    k = l
    while i<n1 and j <n2:
        if a[i] <= b[j]:
            arr[k] = a[i]
            i += 1
            k += 1
        else:
            arr[k] = b[j]
            inv += n1-i
            j += 1
            k += 1
    while i < n1:
        arr[k] = a[i]
        i += 1
        k += 1
    while j < n2:
        arr[k] = b[j]
        j += 1
        k += 1
    return inv
def ms(arr, l, r):
    inv = 0
    if l < r:
        mid = (l+r)//2
        inv += ms(arr, l, mid)
        inv += ms(arr, mid+1, r)
        inv += merge(arr, l, mid, r)
    return inv
infile = open("/content/drive/MyDrive/cse221_ass03/input1.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass03/output1.txt", "w")
l = infile.readlines()
l[0] = l[0].strip("\n")
n = int(l[0])
arr = l[1]
arr = list(map(int, arr.split(" ")))
line = ms(arr, 0, n-1)
outfile.writelines(str(line))