# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WxWCOdGs2ef3fbPXEPlt_bW-J1OzMX4I
"""

def partition(arr, l, r):
    piv = arr[l]
    i = l
    for j in range(l+1, r+1):
        if arr[j] <= piv:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[l], arr[i] = arr[i], arr[l]
    return i
def quickSort(arr, l, r):
    if l < r:
        pi = partition(arr, l, r)
        quickSort(arr, l, pi-1)
        quickSort(arr, pi+1, r)
    return arr

infile = open("/content/drive/MyDrive/cse221_ass03/input3.txt", "r")
outfile = open("/content/drive/MyDrive/cse221_ass03/output3.txt", "w")

l = infile.readlines()
l[0] = l[0].strip("\n")
n = int(l[0])
l[1] = l[1].strip("\n")
arr = list(map(int, l[1].split(" ")))
arr = quickSort(arr, 0, len(arr)-1)
lines = ""
for i in range(len(arr)-1):
    lines += str(arr[i]) + " "
lines += str(arr[len(arr)-1])
outfile.writelines(lines)